### ISSUE TITLE
Broken repository homepage link

### ISSUE THREAD

**Issue by legitosaurus** [googlecreativelab/project-oasis#1]
The top repository URL is broken (currently [https://experiments.withgoogle.com/project-oasis](https://experiments.withgoogle.com/project-oasis)) and results in a 404/page not found.

It looks like it should be set to either [ttps://experiments.withgoogle.com/oasis](https://experiments.withgoogle.com/oasis) or [ttps://experiments.withgoogle.com/voice/oasis](https://experiments.withgoogle.com/voice/oasis).

**Comment by stormbeard90** [comment]
Instructions of fabrication and electronics suggests a link to instructions, however there is no link, nor instructions.
