### ISSUE TITLE
Build your own Terrarium Instructions Missing

### ISSUE THREAD

**Issue by stormbeard90** [googlecreativelab/project-oasis#2]
Missing instructions on fabrication and electronics used in the project - despite suggesting these details are available

**Comment by sgmoorthy** [comment]
From code, this is what I could observe  ( haven’t tried the complete build yet )

```
5-24V Peristaltic Pump [Rain Water Dispenser]
12V Perdistaltic Pump [Mist Maker Water Dispenser]
5V Mist Maker modules
5V Adafruit Neopixel High Intensity LEDs
Arduino Nano
Raspberry Pi 3
12v 4 channel relay board module
```

**Comment by TheHung184** [comment]
https://github.com/kenkawakenkenke/tempescope/wiki/1.-Building-OpenTempescope
Take a look at this, if they only use Pump and Mist maker then it will be equivalent to the OpenTempescope.
I am looking for some additional weather effects when found out Project-Oasis but it seems this project is not much different. Maybe some people can add snow or ice XD ( i am living in a tropical so these weather conditions are not need by me  )
